# Generated by Django 5.2.6 on 2025-10-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlocation_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='stops',
        ),
    ]
