# Generated by Django 5.2.6 on 2025-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userlocation_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='walking_distance',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=10),
            preserve_default=False,
        ),
    ]
