# Generated by Django 5.2.6 on 2025-09-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('septa', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=255)),
                ('arrival_time', models.CharField(max_length=255)),
                ('departure_time', models.CharField(max_length=255)),
                ('stop_id', models.CharField(max_length=255)),
                ('stop_sequence', models.CharField(max_length=255)),
                ('stop_headsign', models.CharField(max_length=255)),
                ('pickup_type', models.CharField(max_length=255)),
                ('drop_off_type', models.CharField(max_length=255)),
                ('shape_dist_traveled', models.CharField(max_length=255)),
                ('timepoint', models.CharField(max_length=255)),
            ],
        ),
    ]
