# Generated by Django 5.2.6 on 2025-09-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='users',
        ),
    ]
