# Generated by Django 5.2.6 on 2025-09-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeptaLocation',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.location')),
                ('location_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=255)),
                ('location_id', models.CharField(max_length=255)),
            ],
            bases=('locations.location',),
        ),
    ]
