# Generated by Django 5.2.6 on 2025-09-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_userlocation_location_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
