# Generated by Django 5.2.6 on 2025-09-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_septalocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='septalocation',
            name='userLocations',
            field=models.ManyToManyField(to='locations.userlocation'),
        ),
    ]
