# Generated by Django 5.2.6 on 2025-09-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_septalocation_userlocations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='septalocation',
            old_name='userLocations',
            new_name='user_locations',
        ),
    ]
