# Generated by Django 5.2.6 on 2025-09-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_rename_userlocations_septalocation_user_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='septalocation',
            name='user_locations',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='septa_locations',
            field=models.ManyToManyField(related_name='user_locations', to='locations.septalocation'),
        ),
    ]
