# Generated by Django 5.2.6 on 2025-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_remove_septalocation_user_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='septa_locations',
            field=models.ManyToManyField(related_name='septa_locations', to='locations.septalocation'),
        ),
    ]
