# Generated by Django 5.2.6 on 2025-09-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_userlocation_septa_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='default_septa_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_septa_location', to='locations.septalocation'),
        ),
    ]
