# Generated by Django 5.2.6 on 2025-10-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.URLField()),
                ('agency_timezone', models.CharField(max_length=100)),
                ('agency_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('exception_type', models.IntegerField()),
            ],
            options={
                'unique_together': {('service_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(max_length=255)),
                ('route_desc', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField()),
                ('route_url', models.URLField(blank=True, null=True)),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='locations.location')),
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_desc', models.TextField(blank=True, null=True)),
                ('zone_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_url', models.URLField(blank=True, null=True)),
                ('location_type', models.IntegerField(default=0)),
                ('parent_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.stop')),
            ],
            bases=('locations.location',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=100)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(max_length=10)),
                ('departure_time', models.CharField(max_length=10)),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_type', models.IntegerField(default=0)),
                ('drop_off_type', models.IntegerField(default=0)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.trip')),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
                'unique_together': {('trip', 'stop_sequence')},
            },
        ),
    ]
