# Generated by Django 5.2.6 on 2025-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['trip', 'stop_sequence'], name='trip_sequence_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['stop'], name='stop_idx'),
        ),
    ]
